### ISSUE TITLE
Can't import in tampermonkey

### ISSUE THREAD

**Issue by johnnydement** [WildByDesign/UserStyles#1]
https://github.com/WildByDesign/UserStyles/blame/b8279534fc229f899fcb239f3fe1456922f63d3a/Rectify11-Chrome-Edge.user.styl#L18

![image](https://github.com/WildByDesign/UserStyles/assets/1867306/2cbbbeb3-6fd5-4e32-8065-88f3be63f549)

**Comment by WildByDesign** [comment]
I am not familiar with Tampermonkey at all. Do you know what can be done to fix this?

**Comment by johnnydement** [comment]
No idea, changed to stylish and no problem there ;)

**Comment by WildByDesign** [comment]
Ok sounds good. I will close this issue.
